### ISSUE TITLE
Matrix multiplication gives Array{Any}

### ISSUE THREAD

**Issue by improbable22** [JeffreySarnoff/ArbNumerics.jl#13]
I found this today, surely not the intended behaviour? 
```
julia> (ArbReal.(ones(2,2))) * (ArbReal.(rand(2)))                    
2-element Array{Any,1}:
 0.9037060469208071378233171344618
 0.9037060469208071378233171344618
```
This does not occur with `ArbFloat`. 

Possibly unrelated, I was also surprised by some promotion rules: 
```
julia> promote_type(ArbReal, ArbFloat)                                
Real

julia> promote_type(Float64, ArbFloat)                                
AbstractFloat
```
It looks like those are just coming from following `supertype` up the tree, however in actual use one would surely want some kind of ArbNumerics type.

**Comment by JeffreySarnoff** [comment]
thanks

**Comment by improbable22** [comment]
Here is one more error -- from attempting to work around that using `ArbFloat`, but perhaps unrelated:
```
julia> (ArbFloat.(ones(2,2))) * (ArbFloat.(ones(2,2)))                
ERROR: MethodError: Cannot `convert` an object of type ArbNumerics.ArbFloatMatrix{128} to an object of type ArbNumerics.ArbRealMatrix
```

**Comment by JeffreySarnoff** [comment]
You are running into where I am at in dev. Using matrices is nontrivial if we want to use the accelerated Arb library based matrix multiplication as the matricies are stored row-dominantely unlike Julia.  I have code that deals with this but it is not fully integrated -- when you see types `ArbFloatMatrix` or `ArbRealMatrix` that is what is going on.  Since you have use of this now, I'll see about cleaning that up (or at least hiding those types) tonight. Btw, `rand(ArbFloat,n)` and `rand(ArbReal,n)` do work.

**Comment by JeffreySarnoff** [comment]
I think current master takes care of your concerns.  I will tag it after some more testing.

**Comment by improbable22** [comment]
Cool, I did see some types like `ArbFloatMatrix` around but wasn't sure what to make of them, so just thought I would try. 

Many thanks for taking a look, and for this whole package really. It seems to have several things not found elsewhere.

**Comment by JeffreySarnoff** [comment]
What do you want to do with it?

**Comment by improbable22** [comment]
Am trying to solve something which needs special functions, and `M\v`, and may need higher precision. Until today I was assuming that `*`, and `\`, would call Julia's fall-back routines. But now that I think about it solving `\` may need to know about precision in a way that `*` does not.

**Comment by JeffreySarnoff** [comment]
Please ask if any questions arise.

**Comment by JeffreySarnoff** [comment]
fixed
