### ISSUE TITLE
no method matching eps(::Type{ArbFloat})

### ISSUE THREAD

**Issue by Goysa2** [JeffreySarnoff/ArbNumerics.jl#18]
Hello!

Is there any way to use `eps` with ArbFloat? 
If I do `eps(ArbFloat)` it doesn't work, but it works with `Float32`, `Float64`, `Float128` (with Quadmath) and `BigFloat` 

Thanks!

**Comment by JeffreySarnoff** [comment]
```
julia> using ArbNumerics

julia> eps(one(ArbFloat))
1.175494350822287507968736537222e-38
```
