### ISSUE TITLE
Feature request: more special functions from the Arb C library

### ISSUE THREAD

**Issue by Raulo** [JeffreySarnoff/ArbNumerics.jl#23]
ArbNumerics does not implement all the special functions from Arb C library. Would it be possible to implement them? If it's too much work, is there a guide how the ArbNumerics internals work? I am interested in polylog_si and tried to implement it myself using other special functions as a template but I failed with the following code that crashes with munmap_chunk(): invalid pointer:

```
function polylog_si(s::Int, x::ArbReal{P}, prec::Int=P) where {P}
    z = ArbReal{P}()
    ccall(@libarb(acb_polylog_si), Cvoid, 
              (Ref{ArbReal}, Cint, Ref{ArbReal}, Clong),
              z, s, x, prec)
    return z
end
```

**Comment by JeffreySarnoff** [comment]
I can add it in the next few days.

**Comment by JeffreySarnoff** [comment]
added to master, in version 0.6.6 which is pending merge

```
julia> polylog(0, ArbReal(3))
-1.5 + 0im

julia> polylog(1, ArbReal(3))
-0.6931471805599453094172321214582 - 3.14159265358979323846264338328im

julia> polylog(2, ArbReal(3))
2.320180423313098396406194473703 - 3.451392295223202661433820583818im

julia> polylog(1, ArbComplex(3,1))
-0.8047189562170501873003796666131 + 2.677945044588987122248387151818im
```
(apologies for the delay)
