### ISSUE TITLE
Ownership of the memory

### ISSUE THREAD

**Issue by orkolorko** [JeffreySarnoff/ArbNumerics.jl#28]
This is a delicate issue, probably worth investigating.
I'm not even sure it happens, but it is worth checking because it seems that while using ArbNumerics the memory consumption of Julia goes up really fast.

ArbComplex and ArbReal allocate memory through the use of arb_init and acb_init functions.
The Garbage Collector is not aware of these functions so it may consider ArbComplex and ArbReal objects really small, i.e., never collect them.
So, no memory leak in code, since the finalizers are defined, but maybe they are never called.

A similar issue was dealt with in Nemo:
https://groups.google.com/forum/#!topic/julia-users/IbA7GNF2_R4

I checked the constructor in Nemo and they also use arb_init, so maybe there is no problem going on here, but I think it is worth checking.

**Comment by JeffreySarnoff** [comment]
I asked, everything should get finalized when it is collected and everything should get collected as needed.  There are different modes of allocation/collection so the "when" may vary.

Would you try doing whatever you did to see the memory use climb and then do `julia> Base.GC.gc()` and see if that fixes things .. then repeat building up the memory use and then using `julia> @time Base.GC.gc()` and let me know how long it takes. Maybe I can call the collector explicitly without calling it too often -- not sure how just yet.

**Comment by JeffreySarnoff** [comment]
also try `GC.gc(true)` before starting and let me know if that helps

**Comment by JeffreySarnoff** [comment]
no information that this is specific to my code
