### ISSUE TITLE
log2(x) and log10(x) yield MethodError's when x is an ArbReal.

### ISSUE THREAD

**Issue by StrangeRay** [JeffreySarnoff/ArbNumerics.jl#36]
ArbNumerics overloads `Base.log2()` and `Base.log10()` to accept ArbFloat and ArbReal arguments. These work as intended for ArbFloat arguments but produce `MethodError`s for ArbReal arguments:

```julia
julia> using ArbNumerics

julia> xF = one(ArbFloat)
1.0

julia> xR = one(ArbReal)
1.0

julia> log2(xF) # Ok
0

julia> log10(xF) # Ok
0

julia> log2(xR)
ERROR: MethodError: no method matching log_2(::Type{ArbReal{128}})
Closest candidates are:
  log_2(::ArbReal{P}) where P at /Users/StrangeHeim/.julia/packages/ArbNumerics/XRGZG/src/float/elementary.jl:22
  log_2(::ArbFloat{P}) where P at /Users/StrangeHeim/.julia/packages/ArbNumerics/XRGZG/src/float/elementary.jl:156
Stacktrace:
 [1] log2(::ArbReal{128}, ::ArbReal{128}) at /Users/StrangeHeim/.julia/packages/ArbNumerics/XRGZG/src/float/elementary.jl:29 (repeats 2 times)
 [2] top-level scope at none:0

julia> log10(xR)
ERROR: MethodError: no method matching log_10(::Type{ArbReal{128}})
Closest candidates are:
  log_10(::ArbReal{P}) where P at /Users/StrangeHeim/.julia/packages/ArbNumerics/XRGZG/src/float/elementary.jl:25
  log_10(::ArbFloat{P}) where P at /Users/StrangeHeim/.julia/packages/ArbNumerics/XRGZG/src/float/elementary.jl:159
Stacktrace:
 [1] log10(::ArbReal{128}, ::ArbReal{128}) at /Users/StrangeHeim/.julia/packages/ArbNumerics/XRGZG/src/float/elementary.jl:36 (repeats 2 times)
 [2] top-level scope at none:0
```

The problem arises because the auxiliary functions `log_2` and `log_10` are expecting arguments which are _instances_ of type ArbReal but are provided ArbReal _types_ instead. PR to follow.

**Comment by JeffreySarnoff** [comment]
Thank you - I had a similar problem arise with exp2 and exp10, and did not realize it happens here too.  Your PR is welcome.

**Comment by StrangeRay** [comment]
I concede abject humiliating defeat by the GitHub PR system for suggesting a bug fix. :-) The correction is trivia,l though. Here's the diff:
```
29c29
<     logof2 = iszero(logof2) ? log_2(x) : logof2
---
>     logof2 = iszero(logof2) ? log_2(ArbReal{P}) : logof2
36c36
<     logof10 = iszero(logof10) ? log_10(x) : logof10
---
>     logof10 = iszero(logof10) ? log_10(ArbReal{P}) : logof10
```

**Comment by StrangeRay** [comment]
Oops. The correction is in `elementary.jl`.

**Comment by JeffreySarnoff** [comment]
so, why did you encounter the problem -- do I need a new release?

**Comment by StrangeRay** [comment]
Sorry, I'm a newbie to GitHub and don't know what the ground rules are for "needing a new release." (:-(
In any case, I encountered the problem when I was developing some packages that usesArbNumerics and, specifically, use `log10()`. I intend for my packages to work for all arguments of type `::Real`, including ArbReals and `Unitful` quantities.

**Comment by StrangeRay** [comment]
The bug fix isn't urgent by any means; I can toddle along nicely with a local fix to `elementary.jl`.

**Comment by JeffreySarnoff** [comment]
fixed on master, will appear by default shortly when merged -- thank you
