### ISSUE TITLE
Wrong way promotions? ArbNumerics.promote() "demotes" arguments of type ArbNumber to their least precise common type.

### ISSUE THREAD

**Issue by StrangeRay** [JeffreySarnoff/ArbNumerics.jl#37]
`Base.promote()` returns its arguments promoted to their widest, most precise common type, but `ArbNumerics.promote()` "demotes" arguments of type ArbNumber to their least precise common type, as in the following example:

```julia
julia> x1 = one(Float32)
1.0f0

julia> x2 = one(Float64)
1.0

julia> xF1 = one(ArbFloat{53})
1.0

julia> xF2 = one(ArbFloat{104})
1.0

julia> typeof(promote(x1,x2))   # Ok. Promotes to highest common precision
Tuple{Float64,Float64}

julia> typeof(promote(xF1,xF2)) # ?? "Demotes" to lowest common precision
Tuple{ArbFloat{53},ArbFloat{53}}
```
This behavior is caused by the promotion rule used:
```julia
    promote_rule(::Type{ArbFloat{P}},::Type{ArbFloat{Q}}) where {P,Q} = P<Q ?
        ArbFloat{P} : ArbFloat{Q}
```
but it seems counterintuitive, at least to me, and is inconsistent with the promotion policy for, say, arguments of type `Float32` and `Float64`, which would be promoted to `Float64`. Is this behavior correct, or should the rule be `P>Q ? ArbFloat{P} : ArbFloat{Q}`?

The "demotion" policy also has (counterintuitive) downstream effects on mixed-precision computations. For example:
```julia
julia> typeof(xF1*xF2)
ArbFloat{53}
```

**Comment by JeffreySarnoff** [comment]
It is not a policy, it is a bug.  Thank you for letting me know. Will fix promptly.

**Comment by JeffreySarnoff** [comment]
I am glad that you brought this to my attention -- It deserves prompt attention.

**Comment by StrangeRay** [comment]
> While it makes sense for ArbFloats to behave as Float32/Float64 with regard to promotion -- it is far less clear that ArbReals should ...

Oh. I see what you mean, and of course you do need to tread _very_ carefully here.  \:-/   For what it's worth (very little, I'm afraid, since I'm no expert on interval arithmetic :-), I suspect you'll find that the issue will resolve in favor of treating ArbReal normative promotions the same way FloatXX promotions are treated. My reasoning, such as it is, is based on my reading of [Motivations for an arbitrary precision interval arithmetic and the MPFI library](http://perso.ens-lyon.fr/nathalie.revol/publis/RR05.pdf) by Revol and Rouillier, and, in particular, the discussion in Sec. 5.3. _Approximation of the zeroes of a function_ that starts on p. 15. _The zero-finding algorithm presented there depends crucially on judicious **increases** in precision_, as prescribed in the the algorithm.

**Comment by JeffreySarnoff** [comment]
I understand. My expectation had been that algorithms which increase precision would be doing  so explicitly through variable creation.
```
bits = 100
a = ArbReal(2.0, bits=bits)
b = f(a)
while bits < 200
   bits += 10
   a = ArbReal(a, bits=bits)
   b = f(a)
  ...
end
```

**Comment by StrangeRay** [comment]
Ah, then you're way ahead of me. And, indeed, the functions I'm writing _do_, in fact, explicitly manage precision increases (they are all increases), and they treat ArbFloats and ArbReals on an equal footing; that is, they promote rather than "demote."
