### ISSUE TITLE
Failed to build when updating to 1.0.4

### ISSUE THREAD

**Issue by newptcai** [JeffreySarnoff/ArbNumerics.jl#41]
The errors are
```
   Building ArbNumerics → `~/.julia/packages/ArbNumerics/RtGOq/deps/build.log`
┌ Error: Error building `ArbNumerics`: 
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaMath/GMPBuilder/releases/download/v6.1.2-2/GMP.v6.1.2.x86_64-linux-gnu.tar.gz to /home/xing/.julia/packages/ArbNumerics/RtGOq/deps/usr/downloads/GMP.v6.1.2.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: LoadError: LibraryProduct(nothing, ["libgmp"], :libgmp, "Prefix(/home/xing/.julia/packages/ArbNumerics/RtGOq/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] write_deps_file(::String, ::Array{LibraryProduct,1}; verbose::Bool, isolate::Bool) at /home/xing/.julia/packages/BinaryProvider/GeAtj/src/Products.jl:419
│  [3] write_deps_file(::String, ::Array{LibraryProduct,1}) at /home/xing/.julia/packages/BinaryProvider/GeAtj/src/Products.jl:400
│  [4] top-level scope at /home/xing/.julia/packages/ArbNumerics/RtGOq/deps/build_GMP.v6.1.2.jl:46
│  [5] include(::Module, ::String) at ./Base.jl:377
│  [6] include(::String) at /home/xing/.julia/packages/ArbNumerics/RtGOq/deps/build.jl:38
│  [7] top-level scope at /home/xing/.julia/packages/ArbNumerics/RtGOq/deps/build.jl:38
│  [8] eval(::Module, ::Any) at ./boot.jl:331
│  [9] top-level scope at /home/xing/.julia/packages/ArbNumerics/RtGOq/deps/build.jl:38
│  [10] include(::String) at ./client.jl:439
│  [11] top-level scope at none:5
│ in expression starting at /home/xing/.julia/packages/ArbNumerics/RtGOq/deps/build_GMP.v6.1.2.jl:46
│ in expression starting at /home/xing/.julia/packages/ArbNumerics/RtGOq/deps/build.jl:14
[14:41:22] ######################################################################## 100.0%##O=#  #       [14:41:23] ######################################################################## 100.0%
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:892
```

**Comment by JeffreySarnoff** [comment]
thank you for the note - This is fixed (in that it builds for me, on Windows and should on Mac, Linux although I cannot test those) in #master and v1.0.5 when that merges (pending). Let me know if you have any more difficulty.

**Comment by JeffreySarnoff** [comment]
Also let me know if it works for you.

**Comment by newptcai** [comment]
```
(@v1.4) pkg> add ArbNumerics#master
    Cloning git-repo `https://github.com/JeffreySarnoff/ArbNumerics.jl.git`
   Updating git-repo `https://github.com/JeffreySarnoff/ArbNumerics.jl.git`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [7e558dbc] ↑ ArbNumerics v1.0.4 ⇒ v1.0.5 #master (https://github.com/JeffreySarnoff/ArbNumerics.jl.git)
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [7e558dbc] ↑ ArbNumerics v1.0.4 ⇒ v1.0.5 #master (https://github.com/JeffreySarnoff/ArbNumerics.jl.git)
   Building ArbNumerics → `~/.julia/packages/ArbNumerics/tV06g/deps/build.log`
┌ Error: Error building `ArbNumerics`: 
│ [ Info: Downloading https://github.com/JuliaPackaging/Yggdrasil/releases/download/GMP-v6.1.2-1/GMP.v6.1.2.x86_64-linux-gnu.tar.gz to /home/xing/.julia/packages/ArbNumerics/tV06g/deps/usr/downloads/GMP.v6.1.2.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: LoadError: LibraryProduct(nothing, ["libgmp"], :libgmp, "Prefix(/home/xing/.julia/packages/ArbNumerics/tV06g/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] write_deps_file(::String, ::Array{LibraryProduct,1}; verbose::Bool, isolate::Bool) at /home/xing/.julia/packages/BinaryProvider/GeAtj/src/Products.jl:419
│  [3] top-level scope at /home/xing/.julia/packages/ArbNumerics/tV06g/deps/build_GMP.v6.1.2.jl:48
│  [4] include(::Module, ::String) at ./Base.jl:377
│  [5] include(::String) at /home/xing/.julia/packages/ArbNumerics/tV06g/deps/build.jl:41
│  [6] top-level scope at /home/xing/.julia/packages/ArbNumerics/tV06g/deps/build.jl:41
│  [7] eval(::Module, ::Any) at ./boot.jl:331
│  [8] top-level scope at /home/xing/.julia/packages/ArbNumerics/tV06g/deps/build.jl:41
│  [9] include(::String) at ./client.jl:439
│  [10] top-level scope at none:5
│ in expression starting at /home/xing/.julia/packages/ArbNumerics/tV06g/deps/build_GMP.v6.1.2.jl:48
│ in expression starting at /home/xing/.julia/packages/ArbNumerics/tV06g/deps/build.jl:15
[13:27:49] ######################################################################## 100.0%##O=#  #       [13:27:51] ######################################################################## 100.0%
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:892
```

**Comment by JeffreySarnoff** [comment]
Please show me `versioninfo()`

**Comment by newptcai** [comment]
```
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = gvim --remote-tab-silent
```

**Comment by JeffreySarnoff** [comment]
I was able to install it on a fresh linux install with Julia v1.4.1.
My guess is there is something tangled locally.  Try
```
(@v1.4) pkg> rm -m ArbNumerics
(@v1.4) pkg> rm ArbNumerics            # this probably will warn no such pkg
(@v1.4) pkg> resolve
(@v1.4) pkg> dev https://github.com/JeffreySarnoff/ArbNumerics.jl
# hope that works
julia> using ArbNumerics
```
If not, we need to ask other people.

**Comment by newptcai** [comment]
OK. It works for me know. I created a new environment in `/tmp` and installed `ArbNumerics` there by what you just posted. Somehow this also solved the problem in the default environment when I tried again.

It seems that the Pkg systems is not entirely fool-proof though.

**Comment by StrangeRay** [comment]
@newptcai's error log is a dead ringer for mine, and he first saw the problem about the same time I did, but _he's on Linux and I'm on MacOS:_ 
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 4
```
I tried
```julia
(@v1.4) pkg> rm -m ArbNumerics
(@v1.4) pkg> rm ArbNumerics            # this probably will warn no such pkg
(@v1.4) pkg> resolve
(@v1.4) pkg> dev https://github.com/JeffreySarnoff/ArbNumerics.jl
```
but no joy:
```julia
using ArbNumerics
[ Info: Precompiling ArbNumerics [7e558dbc-694d-5a72-987c-6f4ebed21442]
ERROR: LoadError: LoadError: IOError: realpath: no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error at ./libuv.jl:97 [inlined]
 [2] realpath(::String) at ./path.jl:429
 [3] top-level scope at /Users/StrangeHeim/.julia/dev/ArbNumerics/src/support/arblib.jl:76
 [4] include(::Module, ::String) at ./Base.jl:377
 [5] include(::String) at /Users/StrangeHeim/.julia/dev/ArbNumerics/src/ArbNumerics.jl:8
 [6] top-level scope at /Users/StrangeHeim/.julia/dev/ArbNumerics/src/ArbNumerics.jl:145
 [7] include(::Module, ::String) at ./Base.jl:377
 [8] top-level scope at none:2
 [9] eval at ./boot.jl:331 [inlined]
 [10] eval(::Expr) at ./client.jl:449
 [11] top-level scope at ./none:3
in expression starting at /Users/StrangeHeim/.julia/dev/ArbNumerics/src/support/arblib.jl:43
in expression starting at /Users/StrangeHeim/.julia/dev/ArbNumerics/src/ArbNumerics.jl:145
ERROR: Failed to precompile ArbNumerics [7e558dbc-694d-5a72-987c-6f4ebed21442] to /Users/StrangeHeim/.julia/compiled/v1.4/ArbNumerics/Xn6ml_KjlZN.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
```
and I still can't build `ArbNumerics`.

I don't know how to "create a new environment and install `ArbNumerics` there," but judging by newptcai's experience, that seems to be crucial. It sounds like he built ArbNumerics in `/tmp`, and by doing so, magically cleared up the problem in his default installation.

**Comment by JeffreySarnoff** [comment]
@StrangeRay try
`julia> ]`
`pkg_> rm ArbNumerics`
`pkg_> dev https://github.com/JeffreySarnoff/ArbNumerics.jl`
`julia> using ArbNumerics`

**Comment by JeffreySarnoff** [comment]
@StrangeRay re environments https://julialang.github.io/Pkg.jl/v1/environments/

**Comment by StrangeRay** [comment]
No, this still doesn’t work, per my earlier comment. I’m about to try your suggestion: moving the downloaded libs into my local  /tV06g/ directories that you named.

Thanks for the quick response, by the way.

**Comment by StrangeRay** [comment]
Pre-positioning the *.la's and *.dylib's in my `/tV06g/` directories  and then _immediately_ `using ArbNumerics` (i.e., without `build`ing ArbNumerics) still results in a precompiling error.  If I then attempt to build, I still end up executing `build_GMP.v.6.1.2.jl` and getting the same LoadError as before.

I tried restoring a working ArbNumerics from backup and renaming the working version `/tV06g/` and then immediately making an attempt at `using ArbNumerics` but I still got the precompilation error. Attempting to `build ArbNumerics` failed in the usual way.

I'm now going to try newptcai's approach, namely creating a new env and installing AN there.

**Comment by newptcai** [comment]
The last resort would be simply delete .julia and reinstall all packages.

**Comment by StrangeRay** [comment]
Progress: I've got a stand-alone AN working in a new environment sandbox. Steps: In a terminal:
```shell
$ mkdir ~/Experiments/Julia/buildAN
$ cd  ~/Experiments/Julia/buildAN
$ julia
```
followed by
```julia
]
(@v1.4) pkg> activate .
(buildAN) pkg> add ArbNumerics
^C
julia> using ArbNumerics
julia> ArbFloat(2)*pi
6.283185307179586476925286766559
```
Now let's see if I can use AN in the default env.

**Comment by StrangeRay** [comment]
Yep:
```julia
]
(@v1.4) pkg> add ArbNumerics
(@v1.4) pkg> ^C
julia> using ArbNumerics
[ Info: Precompiling ArbNumerics [7e558dbc-694d-5a72-987c-6f4ebed21442]

julia> ArbFloat(2)pi
6.283185307179586476925286766559
```
Thanks, @newptcai and Jeffrey.

This worked on MacOS and Linux but I have no clue why. There's a message in here somewhere for the `Pkg` maintainers but it is outside the hearing range of mere Julia mortals like me. :-)

**Comment by newptcai** [comment]
Ah, somehow this stops working for me again. I have deleted ArbNumerics from .julia and tried to add it to a new environment. But then I got the same error while building the package. I suppose it's something wrong with Yggdrasil. But I could not debug it with `Debugger.jl`.  With compelled mode, Debugger does not break on the error and without it it takes very very long time to run.

**Comment by StrangeRay** [comment]
I also suspect there's something going on with Yggdrasil. Is there some way to find out if it was updated about the time we started noticing problems?

And I, too, tried to run the debugger on `build_GMP.v.6.1.2.jl` but in my case it just froze my system, which I was running on Atom. I had to  stop julia and restart.

By the way, does it make sense to you that some of the libraries distributed with Yggdrasil aren't actually libraries, they're _links_ to other libraries in the distribution, so they act like aliases. In the GNU Linux distro, for example, there's a symbolic link named `libgmp.so` that links to `libgmp.so.10.3.2`. That works unless the libraries get moved, in which case the the links get broken. It's fine for local build utilities to create symlinks because it has total control of where things are located and can prevent breaking links, but it's not obvious to me that it's okay for the repository to distribute symlinks.

There are symlinks in the Mac library distro, too.

**Comment by newptcai** [comment]
I just created a bug report with `rr` here https://s3.amazonaws.com/julialang-dumps/reports/2020-05-17T07-50-29-newptcai.tar.zst

I did this by
```
using BugReporting
BugReporting.make_interactive_report("rr")
using ArbNumerics
```

**Comment by StrangeRay** [comment]
@newptcai: The *.tar.zst bug report file appears to be empty. It's only 74B long, which looks like header data. When I `unzstd`ed and un`tar`ed it, it came up empty.

**Comment by newptcai** [comment]
@StrangeRay I see. Not sure how to use BugReporting on Julia 1.4 then. Maybe we will need to wait until Julia 1.5.

**Comment by newptcai** [comment]
For anyone who has the same problem, please try delete .julia and reinstall ArbNumerics. This solves my problem.

**Comment by StrangeRay** [comment]
@newptcai: Maybe I misunderstand how the package manager works, but I don't understand how you could you delete `.julia` without, among other things, blowing away all of your other carefully curated packages. Does Julia keep a manifest of all of your previously installed packages that you can use to resurrect your inventory of packages?

**Comment by newptcai** [comment]
@StrangeRay It's fine because for all my packages that I am working on, I have a separate environment.  So once I have delete .julia and I want to work in a package, I just activate the package's environment and use the command instantiate. This automatically install all dependencies.

**Comment by StrangeRay** [comment]
@newptcai Oh, nice! Thanks. I'll make your process part of my work flow.

**Comment by JeffreySarnoff** [comment]
I am reopening this so others can see the solution.  Thanks.

**Comment by StrangeRay** [comment]
@newptcai @JeffreySarnoff I recommend giving step-by-step instructions explaining _exactly_ how to do this safely without accidentally blowing away all of ones `.julia` packages. After taking a closer look, I admit I'm not clear on the process myself.

**Comment by JeffreySarnoff** [comment]
@newptcai You are the person who has done this successfully.  If you would post the step-by-baby-step instructions (start with this action, do it so .. don't forget to _) with any known contingencies and courses-of-action (if this happens then do that) here, I will rewrite it for the world and add it into the Readme and the docs (crediting you).

**Comment by newptcai** [comment]
To be extra cautious, I started with a backup of the whole `~/.julia`. Start a terminal by typing

```shell
cp -r ~/.julia/ ~/Downloads/
```

Then I removed `~/.julia` without mercy 👿.
```shell
rm -rf ~/.julia/
```

This means all my previously installed Julia packages are now gone, but Julia itself (the binary and core packages) are still there.

Most of my project has its own environment. In other words, there are two files `Project.toml` and
`Manifest.tomal` in the directory containing an environment. For example, to play with `Weave.jl`, I
have an environment in `~/Work/weave`. The content of `Project.toml` is quite simple,
which just indicates that this environment needs three dependencies `DSP`, `Plots` and `Weave`.

```toml
[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
```

The content of `Manifest.toml` is a bit more complicated. The first few lines of it are like this.

```toml
# This file is machine-generated - editing it directly is not advised

[[AbstractFFTs]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "051c95d6836228d120f5f4b984dd5aba1624f716"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.5.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
```

What it does, is to indicate what exact packages are installed the last time I modified the
environment. 

These two files allow me to install all the packages needed to run this environment. I can simply to launch Julia `REPL` in the directly where the environment is, `active` the environment, and run the command `instantiate`.

```julia
(@v1.4) pkg> activate . # press ] to get the pkg prompt
 Activating environment at `~/Work/weave/Project.toml`

(weave) pkg> st
Status `~/Work/weave/Project.toml`
→ [717857b8] DSP v0.6.6
  [91a5bcdd] Plots v1.2.4
→ [44d3d7a6] Weave v0.9.4
┌ Warning: Some packages (indicated with a red arrow) are not downloaded, use `instantiate` to instantiate the current environment
└ @ Pkg.Display /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Display.jl:238

(weave) pkg> instantiate
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Installed AbstractFFTs ──────────────── v0.5.0
  Installed Parsers ───────────────────── v1.0.3
  Installed Tables ────────────────────── v1.0.4
  Installed SpecialFunctions ──────────── v0.10.0
  Installed Weave ─────────────────────── v0.9.4
  Installed DataStructures ────────────── v0.17.15
  Installed Plots ─────────────────────── v1.2.4
  Installed DSP ───────────────────────── v0.6.6
  Installed IteratorInterfaceExtensions ─ v1.0.0
  Installed TableTraits ───────────────── v1.0.0
  Installed PlotUtils ─────────────────── v1.0.2
  Installed Mustache ──────────────────── v1.0.2
  Installed DataValueInterfaces ───────── v1.0.0
  Installed FFTW ──────────────────────── v1.2.1
  Installed IntelOpenMP_jll ───────────── v2018.0.3+0
  Installed Polynomials ───────────────── v0.8.0
  Installed IterTools ─────────────────── v1.3.0
  Installed FFTW_jll ──────────────────── v3.3.9+5
  Installed MKL_jll ───────────────────── v2019.0.117+2
  Installed YAML ──────────────────────── v0.4.0
   Building Plots → `~/.julia/packages/Plots/zOV0T/deps/build.log`
   Building FFTW ─→ `~/.julia/packages/FFTW/5DZuu/deps/build.log`
Downloading artifact: IntelOpenMP
######################################################################## 100.0%##O=#  #                               Downloading artifact: FFTW
######################################################################## 100.0%##O=#  #                          

```

To test, I load `Weave` into the `REPL`.

```julia
julia> using Weave
[ Info: Precompiling Weave [44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9]
```

Everything seems to be fine. 😄

Now if you check, you will see a `~/.julia` has been recreated.

```julia
shell> ls ~/.julia # Press ; to get shell prompt
artifacts  compiled  conda  environments  logs	packages  prefs  registries
```

So one last thing is to do is to restore my `config` folder by.
```julia
shell> cp -r ~/Downloads/.julia/config/ ~/.julia
```
and remove the backup
```julia
shell> rm -rf ~/Downloads/.julia/config/
```

**Comment by newptcai** [comment]
https://newptcai.github.io/reinstall-julia.html

**Comment by JeffreySarnoff** [comment]
and https://github.com/JeffreySarnoff/ArbNumerics.jl/issues/81
I will try to update the lib to FLINT tonight.
