### ISSUE TITLE
Imprecise value returned for the incomplete elliptic integral

### ISSUE THREAD

**Issue by kagalenko-m-b** [JeffreySarnoff/ArbNumerics.jl#56]
```
using QuadGK
using ArbNumerics: ArbFloat,elliptic_f,setextrabits

setextrabits(0);
setprecision(512);
phi=big"0.15";m=big"0.81";
bits = 512;base=2;
I=elliptic_f(ArbFloat(phi; bits, base), ArbFloat(m; bits, base));
println("Estimated quadratue error: ", Float64(I0[2]))
println("ArbNumerics error: ", Float64(I-I0[1]))
```
This prints 
> Estimated quadratue error: 1.7795713073256455e-78
> ArbNumerics error: 1.431115519896257e-33

Comparison with mpmath's `ellipf(phi,m)` shows, that numerical quadrature value is accurate.

**Comment by JeffreySarnoff** [comment]
from Wolfram Alpha: EllipticF(0.15, 0.81) = 0.150457316273903245571259142350163726595535485706257388...

Something is incorrect .. my system is hanging .. will pursue tonight

**Comment by kagalenko-m-b** [comment]
julia> I0
(0.150457316273903245571259142350163726595535485706257388543076847526601957084643814732543556318579780433551222479401173413123491524698745152761503138703372898, 1.77957130732564553321627575393202281978566496471877972864056761571474821408425025525963095810902479863467180398179102338940552171113594675441057139272713794e-78)

Mpmath gives 
> In [6]: ellipf(phi,m)
> Out[6]:  mpf('0.150457316273903245571259142350163726595535485706257388543076847526601957084643814732543556318579780433551222479401173413123491524697599978690588512179196446')

Mpmath and I0[1] differ by about 1e-32, I0 and Wolfram's value that  you've posted differ by about 5e-55

**Comment by kagalenko-m-b** [comment]
That issue seems to be fixed, time to close?

**Comment by JeffreySarnoff** [comment]
thanks
