### ISSUE TITLE
Expose mutable arithmetic

### ISSUE THREAD

**Issue by saschatimme** [JeffreySarnoff/ArbNumerics.jl#6]
Could you expose mutable versions of `+`, `-`, `*`, and `/`?
```julia
# Compute x + y and write the result in x
add!(x, y) 
```
These would avoid the allocations of new intermediate numbers, and allow us to extend some of the capabilities of Arb with much less overhead.

**Comment by JeffreySarnoff** [comment]
`add2!` etc in master (both args must be same type, same precision)
