### ISSUE TITLE
`promote_type` is not supposed to be overloaded

### ISSUE THREAD

**Issue by nsajko** [JeffreySarnoff/ArbNumerics.jl#67]
Several methods are added for `promote_type` in [`src/libarb/promote.jl`](https://github.com/JeffreySarnoff/ArbNumerics.jl/blob/8ad37c2eb61e9006eb09be7b2c35961078245a4a/src/libarb/promote.jl). Xref JuliaLang/julia#54138

**Comment by JeffreySarnoff** [comment]
This was intentional.  At the time it was written, this approach worked best. It may well be that over time, as Julia evolved, it is no longer needed.

**Comment by nsajko** [comment]
The fix was reverted so this should be reopened
