### ISSUE TITLE
Julia 1.11 and ArbNumerics issues with promote?

### ISSUE THREAD

**Issue by bcarneirodacunha** [JeffreySarnoff/ArbNumerics.jl#73]
I'm sorry if this is not the right place, but it seems that last homebrew's version of julia 1.11 breaks ArbNumerics. Now errors are issued whenever some operation between ArbNumerics and built-in types are involved:

For instance, if one defines x = ArbComplex(1.242 + 0.243im), asking for 2x prompts the following error:
ERROR: promotion of types Int64 and ArbComplex{128} failed to change any arguments
Stacktrace:
 [1] error(::String, ::String, ::String)
   @ Base ./error.jl:44
 [2] sametype_error(input::Tuple{Int64, ArbComplex{128}})
   @ Base ./promotion.jl:424
 [3] not_sametype(x::Tuple{Int64, ArbComplex{128}}, y::Tuple{Int64, ArbComplex{128}})
   @ Base ./promotion.jl:418
 [4] promote(x::Int64, y::ArbComplex{128})
   @ Base ./promotion.jl:401
 [5] top-level scope
   @ REPL[11]:1

calling promote(2,x) also gives the same error.

**Comment by JeffreySarnoff** [comment]
Right place. Thank you.

**Comment by JeffreySarnoff** [comment]
should be fixed with pending merge
